name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          persist-credentials: false
      - name: Setup dotnet 5.0.100
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: SonarScanner for .NET 5 with pull request decoration support
        uses: highbyte/sonarscan-dotnet@2.0
        with:
          # The key of the SonarQube project
          sonarProjectKey: ${{ secrets.SONAR_TOKEN }}
          # The name of the SonarQube project
          sonarProjectName:  TeamInterject_BillChop
          # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
          sonarOrganization: teaminterject-164531
          dotnetBuildArguments: ./billchop-be